workflows:
  pack-apk-testapp:
    instance_type: linux
    environment:
      groups:
        - default
    scripts: 
      - name: build and upload to testapp.io
        script: |
          bundle install
          bundle exec fastlane android beta --verbose
